FROM nvcr.io/nvidia/cuda:11.1-cudnn8-devel-ubuntu18.04
RUN apt-get update && apt-get install -y python3.7 python3.7-dev python3.7-distutils curl && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.7 1 && \
    update-alternatives --set python /usr/bin/python3.7 && \
    curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py --force-reinstall && \
    rm get-pip.py
COPY ./requirements.txt /tmp/requirements.txt && \
     pip install -r requirements.txt