FROM python:3.7
RUN pip install torch==1.8.1
RUN pip install torchvision==0.9.1
RUN pip install kubernetes==10.0.1
RUN pip install kfp==1.4.0
RUN pip install boto3==1.17.74
RUN pip install kubeflow-katib==0.11.0
RUN pip install kfserving==0.4.1
