apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: kubeflow-user-example-com
spec:
  volumes:
    - name: host-volume
      persistentVolumeClaim:
        claimName: cifar-workspace-read-claim
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: cifar-nfs-pvc
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      volumeMounts:
      - name: host-volume
        mountPath: /mydata
      - name: nfs-volume
        mountPath: /nfs_data