kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cifar-nfs-pvc
  namespace: kubeflow-user-example-com
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi